
#ifndef ICONIC_MEASURE_COMMON_EXPORT_H
#define ICONIC_MEASURE_COMMON_EXPORT_H

#ifdef ICONIC_MEASURE_COMMON_STATIC_DEFINE
#  define ICONIC_MEASURE_COMMON_EXPORT
#  define ICONIC_MEASURE_COMMON_NO_EXPORT
#else
#  ifndef ICONIC_MEASURE_COMMON_EXPORT
#    ifdef IconicMeasureCommon_EXPORTS
        /* We are building this library */
#      define ICONIC_MEASURE_COMMON_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define ICONIC_MEASURE_COMMON_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef ICONIC_MEASURE_COMMON_NO_EXPORT
#    define ICONIC_MEASURE_COMMON_NO_EXPORT 
#  endif
#endif

#ifndef ICONIC_MEASURE_COMMON_DEPRECATED
#  define ICONIC_MEASURE_COMMON_DEPRECATED __declspec(deprecated)
#endif

#ifndef ICONIC_MEASURE_COMMON_DEPRECATED_EXPORT
#  define ICONIC_MEASURE_COMMON_DEPRECATED_EXPORT ICONIC_MEASURE_COMMON_EXPORT ICONIC_MEASURE_COMMON_DEPRECATED
#endif

#ifndef ICONIC_MEASURE_COMMON_DEPRECATED_NO_EXPORT
#  define ICONIC_MEASURE_COMMON_DEPRECATED_NO_EXPORT ICONIC_MEASURE_COMMON_NO_EXPORT ICONIC_MEASURE_COMMON_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef ICONIC_MEASURE_COMMON_NO_DEPRECATED
#    define ICONIC_MEASURE_COMMON_NO_DEPRECATED
#  endif
#endif

#endif /* ICONIC_MEASURE_COMMON_EXPORT_H */
